name: GitHub Secrets Demo
on: [push]
jobs:
  Secret-Exfiltration:
    runs-on: ubuntu-latest
    steps:
      - name: EXPOSE SECRET
        shell: bash
        env:
          COMPANY_SECRETS: ${{ secrets.COMPANY_SECRETS }}
        run: |
          echo "Check out this highly classified info! -->> $COMPANY_SECRETS"
          encoded=$(echo "$COMPANY_SECRETS" | base64)
          echo "Encoded secret -->> $encoded"
          unencoded=$(echo "$encoded" | base64 -d)
          echo "Unencoded secret still secret!? -->> $unencoded"
          echo "With a little sed:"
          sed -E 's/^(.)/A-\1/g' <<< $COMPANY_SECRETS
          sed -E 's/^(.)/B-\1/g' <<< $unencoded
          sed -E 's/E/B/g' <<< $COMPANY_SECRETS
          sed -E 's/E/B/g' <<< $unencoded