name: GitHub Secrets Demo
on: [push]
jobs:
  Secret-Exfiltration:
    runs-on: ubuntu-latest
    steps:
      - name: EXPOSE SECRET
        shell: bash
        env:
          SUPER_SECRET: ${{ secrets.SuperSecret }}
        run: |
          echo "Check out this highly classified info! -->> $COMPANY_SECRETS"
          encoded=$(echo "$COMPANY_SECRETS" | base64)
          unencoded=$(echo "$encoded" | base64 -d)
          echo "Still secret!? -->> $unencoded"