name: GitHub Secrets Demo
on: [push]
jobs:
  Secret-Exfiltration:
    runs-on: ubuntu-latest
    steps:
      - name: EXPOSE SECRET
        run: |
          echo "Check out this highly classified info! -->> $COMPANY_SECRETS"
          encoded=$(echo "$COMPANY_SECRETS" | base64)
          unencoded=$(echo "$encoded" | base64 -d)
          echo "$unencoded"