name: GitHub Secrets Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: EXPOSE SECRET
        run: |
          echo "Check out this highly classified info! -->> $COMPANY_SECRETS"